// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDESvPN1z1DvQbhnO0PCWau4Mhng9MxotM',
    appId: '1:623859680979:web:93332d2e3e15efc7677626',
    messagingSenderId: '623859680979',
    projectId: 'aplicacion-3abdb',
    authDomain: 'aplicacion-3abdb.firebaseapp.com',
    storageBucket: 'aplicacion-3abdb.firebasestorage.app',
    measurementId: 'G-PQ7V5MF7PW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzNXmUNgizGlQpkIsRChvVuv3u6KVSzI8',
    appId: '1:623859680979:android:72c32f238a7a4b88677626',
    messagingSenderId: '623859680979',
    projectId: 'aplicacion-3abdb',
    storageBucket: 'aplicacion-3abdb.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGT1qTP9NjeBgqZmddARRRh5rU-3IlxbU',
    appId: '1:623859680979:ios:f0752865ddc8961a677626',
    messagingSenderId: '623859680979',
    projectId: 'aplicacion-3abdb',
    storageBucket: 'aplicacion-3abdb.firebasestorage.app',
    iosBundleId: 'com.example.aplicacion',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGT1qTP9NjeBgqZmddARRRh5rU-3IlxbU',
    appId: '1:623859680979:ios:f0752865ddc8961a677626',
    messagingSenderId: '623859680979',
    projectId: 'aplicacion-3abdb',
    storageBucket: 'aplicacion-3abdb.firebasestorage.app',
    iosBundleId: 'com.example.aplicacion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDESvPN1z1DvQbhnO0PCWau4Mhng9MxotM',
    appId: '1:623859680979:web:eb0a512cfc80fcb5677626',
    messagingSenderId: '623859680979',
    projectId: 'aplicacion-3abdb',
    authDomain: 'aplicacion-3abdb.firebaseapp.com',
    storageBucket: 'aplicacion-3abdb.firebasestorage.app',
    measurementId: 'G-JLWEXP8T7B',
  );
}
